server:
  port: 8002

spring:
  application:
    name: demo-provider
  cloud:
    consul:
      host: 192.168.1.45
      port: 80
#      host: localhost
#      port: 8500
      discovery:
        preferIpAddress: true
        heartbeat:
          enabled: true
          ttlValue: 15
          ttlUnit: s
      instanceId: ${spring.application.name}
      config:
        enabled: true

logging:
  level:
    ROOT: INFO
    org.springframework.cloud.sleuth.log: TRACE
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.consul: TRACE

  # path: /var/log/tsf/demo
  file: /var/log/tsf/demo/demo-provider.log
