apiVersion: v1
kind: Pod
metadata:
  name: provider
spec:

  restartPolicy: Never

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:

  - name: provider-ctr
    image: 172.16.0.32:60080/tsf/provider
    volumeMounts:
    - name: shared-data
      mountPath: /app/servlet/logs

  - name: filebeat-ctr
    image: 172.16.0.32:60080/tsf/agent
    env:
      - name: INSTANCE_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: LOCAL_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: APP_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: NAMESPACE_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: ES_HOSTS
        value: "'192.168.1.37:9200','192.168.1.38:9200','192.168.1.40:9200'"
    volumeMounts:
    - name: shared-data
      mountPath: /app/servlet/logs
#      readOnly: true
